"""Add active column to products

Revision ID: 1e1e9875176c
Revises: eacddfd40a42
Create Date: 2025-12-14 23:02:27.566934

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1e1e9875176c"
down_revision = "eacddfd40a42"
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("active", sa.Boolean(), nullable=False, server_default=sa.true())
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_column("active")

    # ### end Alembic commands ###
