"""Add created_at field

Revision ID: 95687cfe9f87
Revises: 1e1e9875176c
Create Date: 2025-12-14 23:15:25.585537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95687cfe9f87'
down_revision = '1e1e9875176c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
